### ISSUE TITLE
decrypt on esp32

### ISSUE THREAD

**Issue by eadmaster** [Northstrix/In-Browser-File-Encrypter#1]
Can you add an example/sketch on how to decrypt on an esp32?

**Comment by Northstrix** [comment]
No, I won't add an ESP32 example as it's infeasible to use the ESP32 for that, though it's theoretically possible and could be implemented in a couple of days.
It takes a while for the ESP32 to derive a key even with ~70,000 PBKDF2-SHA256 iterations. It would probably take the ESP32 several hours to run the PBKDF2-SHA512 with roughly ~10 million iterations (which is this web app is designed for), assuming, of course, that it won't reboot in the process. Additionally, the ESP32 can barely decrypt data 650 bytes without rebooting.

**Comment by eadmaster** [comment]
no problem, i'm trying to implement something similar [here](https://github.com/pr3y/Bruce/issues/123#issuecomment-2295314095) and i'm considering the various options i have.

I've tried with 10k PBKDF2-SHA256 iterations and speed looked reasonable, but i am still not able to get compatibility with the webcrypto output.

The easier solution looks to do both encryption and decryption on the esp32 backend side, but i'd like the idea to move the encryption on the frontend side for better security.
